### ISSUE TITLE
Add linkedin profile link to hero image

### ISSUE THREAD

**Issue by aniketartani** [Evavic44/Victor#12]
On your website, when we click on your profile picture if your LinkedIn id opens then it will be a more interactive website.

**Comment by Evavic44** [comment]
> 
> 
> On your website, when we click on your profile picture if your LinkedIn id opens then it will be a more interactive website.

That is quite an interesting idea. Can you implement that?

**Comment by aniketartani** [comment]
Yes! I can assign me this issue.

**Comment by aniketartani** [comment]
@Evavic44 Once assigned, I will implement it asap.
