### ISSUE TITLE
Is the line btn Tailwindcss & Open source intentional?

### ISSUE THREAD

**Issue by tonycharles377** [Evavic44/Victor#92]
![Capture](https://user-images.githubusercontent.com/98338918/197538679-d25d5bf6-07ba-4161-886c-8ddb186ba31e.PNG)

**Comment by Evavic44** [comment]
Lol. Yes, it is. I was a total noob when I built this portfolio so my design sense was a bit lacking. 😅 The space was to separate my skills from my activities.

**Comment by tonycharles377** [comment]
😂ok. no, it's great and I'm learning a lot from your portfolio.
