### ISSUE TITLE
Twitter fails to redirect to correct page 

### ISSUE THREAD

**Issue by TheYuriG** [Evavic44/Victor#93]
As far as I've seen, every Twitter button redirects to the wrong page (https://twitter.com/evavic44). This doesn't match your actual current Twitter handle.

I don't know if you updated your Twitter handle since creating the website and forgot to update it or if this is an oversight, but i thought it was important to let you know. :)

**Comment by Evavic44** [comment]
Thanks for raising an issue for this, @TheYuriG Feel free to push a fix. ⚡

**Comment by TheYuriG** [comment]
I'm away from my desktop until the 26th, but if it's still pending by then, I'll make the relevant PR. :)

**Comment by TheYuriG** [comment]
Created relevant PR at #96, closing this now as I assume this issue will now be fixed.
