### ISSUE TITLE
You should use dark mode icon.

### ISSUE THREAD

**Issue by vats147** [Evavic44/Victor#99]
Recently I Visited your website there is one problem that is you should use dark mode and light mode icon so it will enhance user experience 

You can refer below image 
![image](https://github.com/Evavic44/Eke/assets/89577062/a48f1919-da70-4b74-b9ab-6b6903329600)

**Comment by Evavic44** [comment]
Actually, I haven't updated this portfolio for ages because I'm looking to decommission it.
